### ISSUE TITLE
Comments left narrow

### ISSUE THREAD

**Issue by Djones4822** [soundjester/lemmy_monkey#12]
I noticed on a post that my comment was staying pretty narrow width. Was that intentional? I think this could be widened a bit for improved readability, but it's up to you. 

![image](https://github.com/soundjester/lemmy_monkey/assets/416715/c0082f0d-210f-4f4e-bdae-223918f91f4d)

**Comment by soundjester** [comment]
it is intentional.  old.reddit does this too, where it limits the comment width.

You can adjust it by looking for `GM_addStyle(".comment p { max-width: 840px; }");` about line 88 (under the "Comments" area) and tweaking or removing this line.

**Comment by Djones4822** [comment]
You're right they do, but the width is the same as the post width. For example here is an old.reddit post on my monitor vs a lemmy post, notice that the post width is constrainted to the same max width, while the post title can extend the whole screen. 

Do you want to emulate that or are you good as is, not trying to push either way, just wanted to point it out.

![image](https://github.com/soundjester/lemmy_monkey/assets/416715/5193915f-9268-400b-84f4-31f0b4f6e78a)

![image](https://github.com/soundjester/lemmy_monkey/assets/416715/1ee13237-45f0-42cb-a106-4d7b3abe2644)

**Comment by soundjester** [comment]
yeah, I'd prefer to limit the post width as well, to have everything in line (similar to your reddit screenshot) - it is proving difficult to do without messing with the main page.

The 840px is a compromise - I'm not too keen on using a fixed width item, but that's as good as I could get.  I'm open to suggestions.  

I do not like overly wide comments (or posts).  Having to scan a good chunk of 1980px is tiring on my poor eyes.

**Comment by Djones4822** [comment]
I have some ideas I can play with and see what works,. I'm always concerned about unintended consequences with the userscripts so I'll let you know if I find anything effective.

**Comment by soundjester** [comment]
indeed.  

I have a dev branch going now (an actual workflow?!?) and the big change there is getting rid of the deprecated greasemonkey addStyles function.  It should make the CSS more portable, at any rate.
