### ISSUE TITLE
Comments get indented in inbox

### ISSUE THREAD

**Issue by DogmaDragon** [soundjester/lemmy_monkey#13]
When opening inbox, unrelated comments gets indented after the latest one when looking at All tab, but if switched to Replies, it displays as intended. 
Caused by https://github.com/soundjester/lemmy_monkey/blob/main/old.reddit.user.js#L89

Userscript: old.reddit.user.js
Version: 1.9.5.2

**Comment by soundjester** [comment]
yes, this is being resolved in the next release.

https://github.com/soundjester/lemmy_monkey/blob/e697d5799ea6944f714d81e57c3059832bc85f8f/old.reddit.compact.user.js#L170

**Comment by soundjester** [comment]
new version (v1.10) pushed
