### ISSUE TITLE
Layout issue with 0.18.1-rc1

### ISSUE THREAD

**Issue by Taijk-nl** [soundjester/lemmy_monkey#30]
The RC1 version being run on feddit.nl seems to give layout issues.

![image](https://github.com/soundjester/lemmy_monkey/assets/20067015/0dce624d-b688-41ee-9c04-30c4b330fdb2)

**Comment by soundjester** [comment]
this class modification is the primary culprit and should be removed:

https://github.com/soundjester/lemmy_monkey/blob/08af593f4008cd9c094c9ae4ebcd2905a678f53f/old.reddit.compact.user.js#L235

**Comment by soundjester** [comment]
I will not update the code directly for this UI RC (0.18.1-rc.2) until the official version is released.  It seems to be missing some fundamental items (eg, ids, bootstrap v5 classes) that either exist in v0.18 or are planned for the next UI.

That said, the changes made here do not negatively impact v0.18, so I will push them in the next update.

**Comment by Taijk-nl** [comment]
Yeah i cam imagine not updating to accommodate the RC. I posted anyway to give you a heads up on a potential issue if this will carry over to the stable release. It is not unusable for me at this time so I can wait.

**Comment by soundjester** [comment]
if you are willing, can you test this script and see how it goes?

https://github.com/soundjester/lemmy_monkey/blob/dev-v.01-Lemmy-v.18.1/old.reddit.compact.user.js

**Comment by Taijk-nl** [comment]
Site has been updated in the mean time to:
UI: 0.18.1-rc5
BE: 0.18.1-rc4

but the script seems to work, layout is fine now. Thanks! the dutch site seems to update to RC's regularly.
ill close this issue now.
