### ISSUE TITLE
Could you try to modify this user script so the horizontal space would be better utilized?

### ISSUE THREAD

**Issue by aki-k** [soundjester/lemmy_monkey#31]
Here's a screenshot what I see on lemmy.world currently:

[https://i.imgur.com/rrAANMm.png](https://i.imgur.com/rrAANMm.png)

Thanks for creating this user script.

Aki

**Comment by soundjester** [comment]
update to latest (v2.5) and let me know how it goes:  

https://greasyfork.org/en/scripts/469093-compact-lemmy-to-old-reddit-re-format-lemmy-v0-18

**Comment by aki-k** [comment]
I installed that v2.5 version but it still leaves a gap (un-utilized space) between the titles and the right side vertical bar:

https://i.imgur.com/wtGjEJa.png

**Comment by soundjester** [comment]
I see the issue.  Most of the code here is for widescreen, with screens below 1400px wide needing additional/modified styles.  I've updated the next version to hopefully help address this.  

If you like, you can check it out here:  

https://github.com/soundjester/lemmy_monkey/raw/dev-.2.6-Lemmy-v0.18.0/old.reddit.compact.user.js

**Comment by aki-k** [comment]
You're amazing. It looks better now:

https://i.imgur.com/B0PDlnK.png

Thank you and best regards,

Aki

**Comment by soundjester** [comment]
I appreciate the assist!  It's tough to troubleshoot layouts on a screen you don't have, so those screenshots really help.

I'm going to mark this as resolved in the next update.

**Comment by soundjester** [comment]
This change has been pushed with v2.6
