### ISSUE TITLE
You may be able to replace MoveCommentCollapseButton() with clever CSS

### ISSUE THREAD

**Issue by wont-work** [soundjester/lemmy_monkey#5]
See https://gist.github.com/ShittyKopper/7c812a68b815fa6f93501e0596c2cdee#file-lemmy-user-css-L73

Just making things a bit more efficient

**Comment by soundjester** [comment]
yes, there are a number of CSS items that need re-work  - mostly waiting until 0.18 is released, as that will require essentially a full rewrite/refactor

**Comment by soundjester** [comment]
I'm incorporating this into the next update - with attribution.  Thanks!
