### ISSUE TITLE
Opening a post in a new tab disables the userscript for the new tab

### ISSUE THREAD

**Issue by Christoph-Wagner** [soundjester/lemmy_monkey#6]
I’m honestly not quite sure what’s happening here.

I open a post in a new tab, the userscript is not applied any more. Navigating around *or even pressing F5* does nothing, only Ctrl+F5 brings back the script (edit: sometimes, during testing, I also managed to get to a state where nothing but closing the tab would work).

I sometimes see  `Error: page.tabs[tab.id] is undefined` and other times `Uncaught TypeError: addedNode.matches is not a function`, those only seem to show up with the script enabled, the first only when it doesn’t work, the 2nd funnily enough only when it works :D 

Script: old.reddit.compact.user.js
Instance: https://discuss.tchncs.de
Browser: FF 114 on Win
Extension: Violentmonkey (OSS and no tracking version of Tampermonkey)

**Comment by soundjester** [comment]
that sounds like the function that moves the comment collapse button.

Try the following (if you are able): comment out line 165: ` ApplyMoveCommentCollapseButton(document.documentElement);` and reload/open new tabs.

**Comment by soundjester** [comment]
This may be resolved in the 1.8 update:

**Comment by Christoph-Wagner** [comment]
Just installed 1.9.4, sadly no change :/

The console errors are gone, but the issue persists.

edit: Also tried Tampermonkey, no change.

**Comment by Christoph-Wagner** [comment]
Okay, the issue was that I used the URL of my instance for the @match metadata. Sorry :/

Though I’d be interested in knowing why that breaks things?

**Comment by soundjester** [comment]
I regularly change my `@match` metadata because I don't like the TLD wildcard activating the script on every non-Lemmy page.  I've not had your issue (yet).

For reference, here's what my script header looks like for v1.9.4:

```
// ==UserScript==
// @name         Compact Lemmy to Old.Reddit Re-format (Observer)
// @namespace    http://tampermonkey.net/
// @version      1.9.4
// @description  Reformat widescreen desktop to look more like Reddit
// @author       mershed_perderders, DarkwingDuck, dx1@lemmy.world, Djones4822
// @match        https://sh.itjust.works/*
// @match        https://lemmy.world/*
// @match        https://lemmy.ml/*
// @match        https://beehaw.org/*
// @match        https://discuss.tchncs.de/*
// @updateURL    https://github.com/soundjester/lemmy_monkey/raw/main/old.reddit.compact.user.js
// @downloadURL  https://github.com/soundjester/lemmy_monkey/raw/main/old.reddit.compact.user.js
// source-url    https://github.com/soundjester/lemmy_monkey/
// ==/UserScript==
```
