### ISSUE TITLE
Padding adjustment to column combos may be too aggressive

### ISSUE THREAD

**Issue by ruffsl** [soundjester/lemmy_monkey#7]
I found unsetting the left padding for `col-12` to be a little too aggressive.
So I commented these lines out locally:

https://github.com/soundjester/lemmy_monkey/blob/f44a3a491181fb49e08b6a14409fcb1059ed99d1/old.reddit.compact.user.js#L95-L96

## Before

![image](https://github.com/soundjester/lemmy_monkey/assets/2293573/19ffe526-1bf0-47f6-bbd4-4861d644fd30)

## After
![image](https://github.com/soundjester/lemmy_monkey/assets/2293573/a465539d-3784-44ff-9381-8db0cdb90aa8)

Would tightening the margins by a percentage, rather than unsetting them be better?

**Comment by soundjester** [comment]
Yes, The script needs some @media adjustments.  As of this writing, the minimum horizontal resolution is about 1280px.  Below that and things do indeed get too smushed...

**Comment by soundjester** [comment]
I have pushed an update that adds screen size adjustments for mobile and smaller screens.

## 1080px:

### main posts

![image](https://github.com/soundjester/lemmy_monkey/assets/11245779/129f2e94-9201-4c8d-ac99-fb28b698cfb0)

### comments

![image](https://github.com/soundjester/lemmy_monkey/assets/11245779/1fdd8042-afa0-4cb7-a227-0fcc27a00d3b)

## 640px:

### main posts

![image](https://github.com/soundjester/lemmy_monkey/assets/11245779/07cfb7e2-8e1f-4b97-8180-a436e5c80e77)

### comments

![image](https://github.com/soundjester/lemmy_monkey/assets/11245779/b60a581c-474d-4b98-8bae-bc7da27f94a8)

**Comment by ruffsl** [comment]
@soundjester , much appreciated! Thank you so much!
