### ISSUE TITLE
Large vote counts can be eclipsed using compact script

### ISSUE THREAD

**Issue by ruffsl** [soundjester/lemmy_monkey#8]
![image](https://github.com/soundjester/lemmy_monkey/assets/2293573/18586c3e-4561-46cd-a21c-91b1816d338a)

Admittedly, this screenshot shows browser at 200% zoom, but looks fine at 100% zoom.

**Comment by soundjester** [comment]
duplicate of https://github.com/soundjester/lemmy_monkey/issues/7

**Comment by Taijk-nl** [comment]
Don't know if it matters, but the "not planned" reason for closing, should that not be "duplicate"?

**Comment by DogmaDragon** [comment]
> Don't know if it matters, but the "not planned" reason for closing, should that not be "duplicate"?

It's a general term GitHub uses.
![image](https://github.com/soundjester/lemmy_monkey/assets/103123951/a521c0f3-3649-4755-8674-c83f37f2325b)
